app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*
 */


//rutas para el recurso movie //
Route::resource('movie','MovieController');

//una nueva ruta para eliminar registros con el metodo get//
Route::get('movie/destroy/{id}',['as' => 'movie/destroy','uses' =>'MovieController@destroy']);

//ruta para realizar busqueda de registros//
Route::post('movie/search',['as' => 'movie/search', 'uses' => 'MovieController@search']);

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Models/Movie.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Movie extends Model {
    protected $table = 'movies';
    protected  $fillable = ['name','description'];
    protected $guarded =['id'];


	//

}

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

}

app/Http/Controllers/Controller.php
<?php namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesCommands;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController {

	use DispatchesCommands, ValidatesRequests;

}

app/Http/Controllers/HomeController.php
<?php namespace App\Http\Controllers;

class HomeController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Home Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders your application's "dashboard" for users that
	| are authenticated. Of course, you are free to change or remove the
	| controller as you wish. It is just here to get your app started!
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('home');
	}

}

app/Http/Controllers/MovieController.php
<?php namespace App\Http\Controllers;

use App\Models\Movie as Movie;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class MovieController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $movies = Movie::all();
        return \View::make('list', compact('movies'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return \View::make('new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $movie = new Movie;
        $movie->name = $request->name;
        $movie->description = $request->description;
        $movie->save();
        return redirect('movie');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $movie = Movie::find($id);
        return \View::make('update', compact('movie'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update(Request $request)
    {
        $movie = Movie::find($request->id);
        $movie->name = $request->name;
        $movie->description = $request->description;
        $movie->save();
        return redirect('movie');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function search(Request $request)
    {
        $movies = Movie::where('name', 'like', '%' . $request->name . '%')->get();
        return \View::make('list', compact('movies'));
    }

    public function destroy($id)
    {
        $movie = Movie::find($id);
        $movie->delete();
        return redirect()->back();


    }
}

app/Http/Controllers/WelcomeController.php
<?php namespace App\Http\Controllers;

class WelcomeController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Welcome Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders the "marketing page" for the application and
	| is configured to only allow guests. Like most of the other sample
	| controllers, you are free to modify or remove it as you desire.
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('guest');
	}

	/**
	 * Show the application welcome screen to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('welcome');
	}

}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Laravel</title>

	<link href="{{ asset('/css/app.css') }}" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Laravel</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{{ url('/') }}">Home</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="{{ url('/auth/login') }}">Login</a></li>
						<li><a href="{{ url('/auth/register') }}">Register</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					You are logged in!
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/list.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            {!! Form::open(['route'=> 'movie/search', 'method' => 'post', 'novalidate','class' => 'form-inline']) !!}
            <div class="form-group">
                <label for="exampleInputName2"> Name </label>
                <input type="text" class= "form-control" name= "name">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
            <a href="{{route('movie.index')}}" class="btn btn-primary">All</a>
            <a href="{{route('movie.create')}}" class="btn btn-primary">Create</a>
            {!! Form::close() !!}
            <br>
            <table class="table table-condensed table-striped table-bordered">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($movies as $movie)
                    <tr>
                        <td>{{$movie->name}}</td>
                        <td>{{$movie->description}}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="{{ route('movie.edit', ['id' => $movie->id])}}" >Edit</a>
                            <a class="btn btn-danger btn-xs" href="{{ route('movie/destroy', ['id' => $movie->id])}}" >Delete</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/new.blade.php
@extends('app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!!Form::open(['route' => 'movie.store', 'method' => 'post', 'novalidate'])!!}
                    <div class="form-group">
                    {!!Form::label('full_name','Nombre')!!}
                    {!!Form::text('name', null, ['class' => 'form-control','required' => 'required'])!!}
                    </div>

                <div class="form-group">
                    {!!Form::label('email','Descripci&oacute;n')!!}
                    {!!Form::text('description', null, ['class' => 'form-control','required' => 'required'])!!}
                    </div>

                <div class="form-group">
                    {!!Form::submit('Enviar',['class' => 'btn btn-success'])!!}
                    </div>
                     {!!Form::close()!!}
                    </div>
                </div>
            </div>
@endsection

resources/views/update.blade.php
@extends('app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
             {!!Form::model($movie,['route'=> 'movie.update', 'method' =>'put', 'novalidate'])!!}
                {!!Form::hidden('id',$movie->id)!!}
                <div class="form-group">
                    {!!Form::label('full_name','Nombre')!!}
                    {!!Form::text('name', null, ['class' => 'form-control','required' => 'required'])!!}
                </div>

                <div class="form-group">
                    {!!Form::label('email','Descripci&oacute;n')!!}
                    {!!Form::text('description', null, ['class' => 'form-control','required' => 'required'])!!}
                </div>

                <div class="form-group">
                    {!!Form::submit('Enviar',['class' => 'btn btn-success'])!!}
                </div>
                {!!Form::close()!!}
            </div>
        </div>
    </div>
@endsection